articles/urls.py
from django.urls import path

from . import views

app_name = "articles"
urlpatterns = [
    path("<slug:slug>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("", views.ArticleListView.as_view(), name="article-list"),
]

cfeblog/urls.py
from articles.views import ArticleHomeView
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", ArticleHomeView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone

from . import utils

User = settings.AUTH_USER_MODEL  # defaults to 'auth.User'


class ArticleQuerySet(models.QuerySet):
    def published(self):
        now = timezone.now()
        return self.filter(publish_status=Article.ArticlePublishOptions.PUBLISH).filter(
            Q(publish_timestamp__lte=now) | Q(user_publish_timestamp__lte=now)
        )

    def pending_published(self):
        now = timezone.now()
        return self.filter(publish_status=Article.ArticlePublishOptions.PUBLISH).filter(
            Q(publish_timestamp__gt=now) | Q(user_publish_timestamp__gt=now)
        )

    def drafts(self):
        return self.filter(publish_status=Article.ArticlePublishOptions.DRAFT)

    def select_author(self):
        return self.select_related("user")

    def search(self, query=None):
        if query is None:
            return self.none()
        return self.filter(Q(title__icontains=query) | Q(content__icontains=query))


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published().select_author()

    def drafts(self):
        return self.get_queryset().drafts().select_author()

    def pending(self):
        return self.get_queryset().pending_published().select_author()


class Article(models.Model):
    class ArticlePublishOptions(models.TextChoices):
        PUBLISH = "pub", "Publish"
        DRAFT = "dra", "DRAFT"
        PRIVATE = "pri", "Private"

    user = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
    updated_by = models.ForeignKey(
        User, related_name="editor", null=True, blank=True, on_delete=models.SET_NULL
    )
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to=utils.get_article_image_upload_to, null=True, blank=True
    )
    publish_status = models.CharField(
        max_length=3,
        choices=ArticlePublishOptions.choices,
        default=ArticlePublishOptions.DRAFT,
    )
    publish_timestamp = models.DateTimeField(
        help_text="Field-driven publish timestamp",
        auto_now_add=False,
        auto_now=False,
        blank=True,
        null=True,
    )
    user_publish_timestamp = models.DateTimeField(
        help_text="User-defined publish timestamp",
        auto_now_add=False,
        auto_now=False,
        blank=True,
        null=True,
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ArticleManager()

    class Meta:
        ordering = ["-user_publish_timestamp", "-publish_timestamp", "-updated"]

    def get_absolute_url(self):
        return reverse("articles:article-detail", kwargs={"slug": self.slug})

    def get_image_url(self):
        if not self.image:
            return None
        return self.image.url

    @property
    def is_published(self):
        if not self.publish_status == Article.ArticlePublishOptions.PUBLISH:
            return False
        now = timezone.now()
        if self.user_publish_timestamp is not None:
            return self.user_publish_timestamp <= now
        return self.publish_timestamp <= now

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = utils.unique_slug_generator(self)
        if self.user_publish_timestamp:
            """
            User has set user_publish_timestamp,
            Automatically set publish_timestamp
            """
            self.publish_timestamp = self.user_publish_timestamp
        if self.publish_status == Article.ArticlePublishOptions.PUBLISH:
            """
            User has set publish_status to PUBLISH,
            Automatically set publish_timestamp to
            now
            """
            if not self.publish_timestamp:
                self.publish_timestamp = timezone.now()
        super().save(*args, **kwargs)

articles/views.py
from django.views import generic

from .models import Article


class ArticleHomeView(generic.ListView):
    queryset = Article.objects.published()
    paginate_by = 10
    template_name = "articles/article_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Latest Articles"
        return context


class ArticleListView(generic.ListView):
    queryset = Article.objects.published()
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get("q")
        if query is not None:
            return qs.search(query=query)
        return qs


class ArticleDetailView(generic.DetailView):
    queryset = Article.objects.published()

articles/templates/articles/article_detail.html
{% extends "base.html" %}


{% block head_title %}
{{ article.title }} | Articles | {{ block.super }}
{% endblock head_title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 mx-auto col-md-8 col-12">
            <h2>{{ article.title }}</h2>
            {% if article.image %}
            <img class="img-fluid" src="{{ article.get_image_url }}" alt="{{ article.image }}">
            {% endif %}
            <div>
                {{ article.content|linebreaks }}
            </div>
        </div>
    </div>
</div>
   
{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base.html" %}


{% block head_title %}
{% if title %}{{ title }}{% else %}Articles{% endif %} | {{ block.super }}
{% endblock head_title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 mx-auto col-md-8 col-12">
        <h2>{% if title %}{{ title }}{% else %}Articles{% endif %}</h2>
        {% if request.GET.q %}<p>Results for <b>{{ request.GET.q }}</b></p> {% endif %}
            {% for article in object_list %}
                <div class="card">
                    {% if article.image %}
                    <a href="{{ article.get_absolute_url }}">
                        <img class="card-img-top"  src="{{ article.get_image_url }}" alt="{{ article.image }}" />
                    </a>
                    {% endif %}
                    <div class="card-body">
                        <a href="{{ article.get_absolute_url }}"> 
                            <h3 class="card-title">
                                {{ article.title }}
                            </h3>
                        </a>

                        {% if article.content %}<p class="card-text"> {{ article.content|truncatewords:20 }}.</p>{% endif %}
                        <a href="{{ article.get_absolute_url }}" class="btn btn-primary">View</a>
                    </div>
                </div>
            {% empty %}
            <div class="text-center my-5 py-5"><i>No articles found.</i></div>
            
                {% endfor %}


            <nav class="mt-4" aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                  <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                  {% endif %}
                  {% if page_obj.paginator.num_pages > 1 %}
                  <li class="page-item">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</li>
                  {% endif %}
                  {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Last &raquo;</a></li>
                  {% endif %}
                </ul>
              </nav>


            </div>
        </div>

    </div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block head_title %}CFE Django Block{% endblock %}</title>
  </head>
  <body>
      {% include 'navbar.html' %}
    {% block content %}
        <h1>Your templates are working, but your blocks are not. </h1>
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Django Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articles:article-list' %}">Articles</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'articles:article-list' %}">
          <input name="q" class="form-control me-2" type="search" placeholder="Search articles.." aria-label="Search articles" value=" {% if request.GET.q %}{{ request.GET.q }}{% endif %}">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>